# Generated by Django 4.2.5 on 2023-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='athlete',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['-time_create'], name='athletes_at_time_cr_e1a4f5_idx'),
        ),
    ]
