# Generated by Django 4.2.5 on 2023-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_athlete_options_athlete_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
