# Generated by Django 4.2.5 on 2023-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_uploadfiles_alter_athlete_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
