# Generated by Django 4.2.5 on 2023-10-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_category_athlete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.category'),
        ),
    ]
