# Generated by Django 4.2.5 on 2023-10-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athlete_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='athletes.category'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='athletes.tagpost'),
        ),
    ]
